version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/codebase/TestSpringApp
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: change_permissions.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: application_start.sh
    - location: create_test_db.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
      runas: ubuntu
